name: GitHub Action No. 2

on:
  push:
      branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-lates
      steps:
        -name: Checkout
          uses: actions/checkout@v3
        -name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: "16"
          -name: Install Dependencies
            run: npm ci
          -name: Build Project
            run: npm run build
